import java.util.Scanner;
import java.util.ArrayList;

public class RunMyNeuralNetwork
{
    //features
    private static Scanner userScanner = new Scanner ( System.in );
    
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    //run
    public static void main ( String [ ] stuff )
    {
        doTraining ( );
        renderMainMenu ( ); //test neural network
    }
    
    //methods
    public static void renderMainMenu ( )
    {
        System.out.println ( "---August 2, 2024 - Neural Network from scratch practice, G. Bennett" );
        System.out.println ( "[1] Get neural network guess for input = {1,1} " );
        System.out.println ( "[2] Get neural network guess for input = {1,0} " );
        System.out.println ( "[3] Get neural network guess for input = {0,1} " );
        System.out.println ( "[4] Get neural network guess for input = {0,0} " );
        System.out.println ( "[5] Quit program " );
        
        int userInput = userScanner.nextInt ( );
        
        switch ( userInput )
        {
            case 1:
            {
                int inputs [ ] = new int [ ] { 1, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess for input {1,1} = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            }
            break;
            case 2:
            {
                int inputs [ ] = new int [ ] { 1, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess for input {1,0} = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            }
            break;
            case 3:
            {
                int inputs [ ] = new int [ ] { 0, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess for input {0,1} = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            }
            break;
            case 4:
            {
                int inputs [ ] = new int [ ] { 0, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess for input {0,0} = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            }
            break;
            case 5:
            {
                System.out.println ( "Good bye" );
                System.exit ( 0 );
            }
            break;
        }
    }
    
    public static void doTraining ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        
        
        //forward and backward propagation
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
            String trainingDataInputLine = trainingData.get ( tDI ).split ( "::" ) [ 0 ];
            
            int inputA = Integer.parseInt ( trainingDataInputLine.split ( "," ) [ 0 ] );
            int inputB = Integer.parseInt ( trainingDataInputLine.split ( "," ) [ 1 ] );
            
            neuralNetwork.doForwardPropagation ( new int [ ] { inputA, inputB } );
            
            
            int targetData = Integer.parseInt ( trainingData.get ( tDI ).split ( "::" ) [ 1 ] );
            
            neuralNetwork.doBackwardPropagation ( targetData );
        }
    }
    
    public static void returnToMainMenu ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        System.out.println ( "\f" );
        renderMainMenu ( );
    }
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );

        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,1::1" );
        
        return returnValue;
    }
}